services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: go-asyncapi
      POSTGRES_PASSWORD: qwerty
      POSTGRES_USER: admin
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data